"""production changes

Revision ID: 67cf6ef4dc27
Revises: 367f582a6b17
Create Date: 2021-11-15 14:28:14.274704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cf6ef4dc27'
down_revision = '367f582a6b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'title')
    # ### end Alembic commands ###
